# Generated by Django 3.2.25 on 2025-11-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20251120_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/default.jpg.jpg', upload_to='blog/'),
        ),
    ]
